### ISSUE TITLE
First Issue (noob warning)

### ISSUE THREAD

**Issue by Decapitater** [ceuk/mutt_dotfiles#2]
Binding '^X' will alias '^Xe'  Before, try: 'bind compose ^Xe noop'  https://neomutt.org/guide/configuration.html#bind-warnings
Binding '|Tab>' will alias '|'  Before, try: 'bind pager | noop'  https://neomutt.org/guide/configuration.html#bind-warnings
Binding '|Tab>' will alias '|'  Before, try: 'bind index | noop'  https://neomutt.org/guide/configuration.html#bind-warnings
Binding '|Tab>' will alias '|'  Before, try: 'bind compose | noop'  https://neomutt.org/guide/configuration.html#bind-warnings
Binding '|Tab>' will alias '|'  Before, try: 'bind attach | noop'  https://neomutt.org/guide/configuration.html#bind-warnings
Unknown Mailbox: $HOME/.local/share/mail/"name"/Lists.Aerc
Error in $HOME/.config/mutt/accounts/gmail.muttrc, line 32:
Error in  $HOME/.config/mutt/muttrc, line 11: source: file $HOME/.config/mutt/accounts/gmail.muttrc could not be sourced
source: errors in $HOME/.config/mutt/muttrc
@ceuk  
help

**Comment by ceuk** [comment]
Hey, I just pushed a fix for that mailbox error - you need to change the "mailboxes" line in `~/.config/mutt/accounts/gmail.muttrc`

As for the warnings - are you using the latest bindings from the repo? There shouldn't be any any binding conflicts I don't think. 

Check you're using the latest version and if you're still getting the warnings ping me on this issue again

**Comment by Decapitater** [comment]
@ceuk what should i do ? 
i use 2fa , mailbox is empty it did not ask for password 
btw i changed Account Alias with a name every where in conifg file 
it asked $HOME/.local/share/mail/$NAME does not exist and askes to make it when pressed y and then exited and rentered it asks the same

**Comment by Decapitater** [comment]
it says no mailbox

**Comment by ceuk** [comment]
are you using an app password? https://support.google.com/accounts/answer/185833?hl=en

Does making the folder in ~/.local/share/mail/ manually help? I think I've had to do that in the past, can't remember

**Comment by Decapitater** [comment]
yes , 
i removed  your config for the current moment as you were unavailable and i was too  lazy , got mine back (sry) i would again try them back when i have time 
thanks for all the support , good work @ceuk 
Enjoy !

**Comment by codernavi18** [comment]
This did not help. 
For example I created `/home/naveen/.local/share/mail/work/[Gmail].Starred`, but still I get the error

/home/naveen/.config/mutt/accounts/1-examplegmailimap.muttrc:32: Unknown Mailbox: /home/naveen/.local/share/mail/work/[Gmail].Starred
/home/naveen/.config/mutt/muttrc:12: source: file /home/naveen/.config/mutt/accounts/1-examplegmailimap.muttrc could not be sourced
source: errors in /home/naveen/.config/mutt/muttrc
